spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 940419
    url: jdbc:mysql://127.0.0.1/Qixi?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  port: 8080
mybatis:
  configuration:
    call-setters-on-nulls: true
logging:
  level: debug

